# Intro to R Review

### August Guang
### Ellen Duong
### 2024-09-16

## Structure

We will be reviewing through some (not all) of the material again, starting from R Data Structures and giving everyone more time to practice actually writing their own code vs executing. At the end of each review section there will be a set of coding practice questions to answer - you are welcome to work in pairs, but you can work on your own if you need to. All questions we will work on in class.

# 1. R Data Structures

 * We went over:
   * `vector`
   * `matrix`
   * `list`
   * `dataframe`

## 1.1 `vector`

 * `vector` type in R is a 1D array that holds data that is all the same type.
 * The `c()` function combines elements to form a vector

In [1]:
my_vec <- c(42, 137, 34)
my_vec

[1]  42 137  34

## 1.2 Indexing - accessing elements

There are multiple ways to access the elements of a vector (or any other data structure).

 * The `[]` notation is what is used for access.

In [18]:
people <- c("august", "ellen", "paul")
people[1]

[1] "august"

### 1.2.1 Range-based indexing

Range-based indexing allows you to get multiple elements of a vector, or multiple "slices" (i.e. contiguous elements)

In [19]:
people[2:3]

[1] "ellen" "paul"

### 1.2.2 Vector indexing

We can use a vector of integers for indexing when we want multiple elements that are not all one after another

In [20]:
people[c(1,3)]

[1] "august" "paul"

### 1.2.3 Logical (boolean) indexing [new]

We can use logical (or boolean) values to index as well

In [21]:
people[c(TRUE,FALSE,FALSE)]

[1] "august"

### 1.2.4 Modifying elements with indexing [new]

We can use indexing to modify a vector's elements.

In [22]:
people[3] <- "not paul"
people

[1] "august"   "ellen"    "not paul"

You can replace multiple elements all at once:

In [32]:
people[2:3] <- "no one"
people

[1] "august" "no one" "no one" NA       NA       "paul h"

In [33]:
people[2:3] <- c("ellen d", "perhaps paul")
people

[1] "august"       "ellen d"      "perhaps paul" NA             NA            
[6] "paul h"

### 1.2.5 Adding elements or concatenating vectors

You can add elements to a vector by specifying the index you want the element to be added at. R will autofill any indices without a present element at them as `NA`, or missing.

You can also concatenate vectors with the `c()` function.

In [23]:
people[6] <- "paul h"
people

[1] "august"   "ellen"    "not paul" NA         NA         "paul h"

In [25]:
people2 <- c(people, c("paul c", "paul s", "paul x"))
people2

[1] "august"   "ellen"    "not paul" NA         NA         "paul h"   "paul c"  
[8] "paul s"   "paul x"

## 1.3 `matrix`

* 2-dimensional array
* Has to store data of all the same types
* First argument is vector of data to be arranged as a matrix.
* Additional arguments:
    * You use `nrow` to specify the number of rows, and `ncol` to specify the number of columns. These are required arguments, but only 1 is needed.
    * The `byrow` argument will determine whether the values are arranged by row or by column. The default is by column.

In [10]:
m <- matrix(1:12, nrow=3) # specifying nrow as 3
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [37]:
m <- matrix(1:12, ncol=3) # can also have 3 columns instead
m

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [38]:
matrix(1:12, ncol=3, byrow=TRUE) # will set it so that it goes by row instead

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

### 1.3.1 Non-numeric data (new)

We didn't go over this last class, but matrices can store non-numeric data as well, they just all have to be the same type.

In [27]:
matrix(people2, nrow=3)

[,1]     [,2]   [,3]  
[1,] august   NA     paul c
[2,] ellen    NA     paul s
[3,] not paul paul h paul x

### 1.3.2 Matrix indexing

Matrix indexing works much like `vector`, except that now you choose the elements in each dimension with `[,]` notation. Additionally, you can specify a whole row or a whole column.

In [28]:
m[1,2] # first row, second column

[1] 4

In [29]:
m[2,] # just second row

[1]  2  5  8 11

## Review Questions

### 1. How would we make a vector with the following elements?

 * `dog`
 * `cat`
 * `bird`
 * `potato`

In [ ]:
# code for review q
animal_vec <- 0 # replace 0 with what?

### 2. Matrix indexing

Suppose we have the matrix `m` below. How do we get the 2nd and 4th elements from the 3rd column? 

In [39]:
m <- matrix(1:12, ncol=3)
m

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [ ]:
# your code here

Let's say we want to replace these 2 elements with 100 and 100, respectively. How would we do that?

In [40]:
# your code here

### 3. Lists and Dataframes

Last class we also went over `list` and `dataframe` as data structures.

 * How would we make a list with `dog`, `cat`, `bird`, `potato` instead of a vector?
 * How about a list with `dog`, `cat`, `bird`, `potato`, 1, 2, 3?
 * How would we make a dataframe with the same number of columns as `m` above?